// Generated by `npm run db:types`. This placeholder ships so a fresh clone can
// typecheck without first running Supabase locally; once you do run
// `npm run db:types`, this file is overwritten with a fully-typed Database
// interface derived from supabase/migrations/.
//
// Until then the Supabase client is typed as `SupabaseClient<unknown>` and the
// `.from('table')` calls have no compile-time column safety. Treat any
// committed-shaped code that touches the Supabase client as provisional until
// the real types land.

export type Database = unknown;
