// Facilitator dashboard data access. Wraps the `facilitator_session_summary`
// SECURITY DEFINER RPC in the Supabase client. The RPC is its own gate (token
// hash lookup); RLS is not relied on for this read because step 4 predates the
// JWT issuer (deferred to step 6).
//
// We cast the RPC call to the hand-typed `FacilitatorSummary` because the
// shared `Database` type is currently `unknown` (regenerated by
// `npm run db:types`). Once that runs, the cast becomes a no-op narrowing.

import type { FacilitatorSummary } from '$shared/types/api';
import { getSupabase } from './supabase';

export type LoadSessionResult =
  | { ok: true; summary: FacilitatorSummary }
  | { ok: false; reason: 'unconfigured' | 'not-found' | 'error'; message?: string };

export async function loadFacilitatorSession(token: string): Promise<LoadSessionResult> {
  const supabase = getSupabase();
  if (!supabase) {
    return { ok: false, reason: 'unconfigured' };
  }
  if (!token || token.length < 16) {
    return { ok: false, reason: 'not-found' };
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any).rpc('facilitator_session_summary', {
    p_facilitator_token: token,
  });
  if (error) {
    return { ok: false, reason: 'error', message: error.message };
  }
  if (!Array.isArray(data) || data.length === 0) {
    return { ok: false, reason: 'not-found' };
  }
  const summary = data[0] as FacilitatorSummary;
  return { ok: true, summary };
}

/**
 * Group score values by their owning map. Tracks marked `shared_with_map_ids`
 * are appended to each shared map's group as well as their owning map's group,
 * with a `shared_from_map_id` flag so the UI can label the duplicate. Spec
 * section 13.5 (shared War Progress).
 */
export interface MapScoreGroup {
  map_id: string;
  map_name: string;
  map_sort_order: number;
  tracks: Array<FacilitatorScoreEntry>;
}

export interface FacilitatorScoreEntry {
  score_track_id: string;
  track_name: string;
  current_value: number;
  min_value: number;
  max_value: number;
  visible_to_players: boolean;
  is_shared_in_from?: string | null;
}

export function groupScoresByMap(
  scoreValues: FacilitatorSummary['score_values'],
): MapScoreGroup[] {
  const byMap = new Map<string, MapScoreGroup>();

  for (const sv of scoreValues) {
    if (!byMap.has(sv.map_id)) {
      byMap.set(sv.map_id, {
        map_id: sv.map_id,
        map_name: sv.map_name,
        map_sort_order: sv.map_sort_order,
        tracks: [],
      });
    }
    byMap.get(sv.map_id)!.tracks.push({
      score_track_id: sv.score_track_id,
      track_name: sv.track_name,
      current_value: sv.current_value,
      min_value: sv.min_value,
      max_value: sv.max_value,
      visible_to_players: sv.visible_to_players,
      is_shared_in_from: null,
    });
  }

  // For each track that lists shared_with_map_ids, surface it on those maps
  // too with a back-pointer to its origin.
  for (const sv of scoreValues) {
    for (const otherMap of sv.shared_with_map_ids ?? []) {
      const target = byMap.get(otherMap);
      if (!target) continue;
      if (target.tracks.some((t) => t.score_track_id === sv.score_track_id)) continue;
      target.tracks.push({
        score_track_id: sv.score_track_id,
        track_name: sv.track_name,
        current_value: sv.current_value,
        min_value: sv.min_value,
        max_value: sv.max_value,
        visible_to_players: sv.visible_to_players,
        is_shared_in_from: sv.map_id,
      });
    }
  }

  return Array.from(byMap.values()).sort((a, b) => a.map_sort_order - b.map_sort_order);
}
