-- 0001_init.sql
-- Crisis: Mars web runner schema, mirroring spec section 24.
-- Conventions:
--   * uuid primary keys, generated by gen_random_uuid()
--   * timestamptz for all dates
--   * Enums for status fields with a fixed vocabulary
--   * Foreign keys are NOT NULL except where the column is genuinely optional
--   * RLS is enabled on every table here but no policies are added until 0002_rls.sql
--   * The seed script (scripts/seed-from-scenario.mjs) populates the static lookup
--     tables (scenario, faction, role, role_availability, map, map_score_track,
--     map_location, card_template). Runtime tables are written by the app.

create extension if not exists pgcrypto;

-- =============================================================================
-- Enums (locked vocabulary)
-- =============================================================================

create type participant_type as enum ('player', 'facilitator', 'npc', 'observer');

create type permission_level as enum ('player', 'facilitator', 'observer');

create type session_status as enum ('draft', 'live', 'paused', 'ended', 'archived');

create type phase_kind as enum (
  'prologue',
  'team',
  'negotiation',
  'action',
  'epilogue'
);

create type card_type as enum ('action', 'resource');

create type card_state as enum (
  'held',
  'offered',
  'committed',
  'accepted',
  'rejected',
  'spent',
  'reclaimed',
  'voided'
);

create type action_status as enum (
  'in_hand',
  'placed',
  'called',
  'resolving',
  'resolved',
  'returned'
);

create type opportunity_status as enum ('pending', 'offered', 'chosen', 'expired', 'resolved');

create type trade_status as enum ('proposed', 'confirmed', 'cancelled', 'expired');

create type token_status as enum ('active', 'rotated', 'locked', 'revoked');

-- =============================================================================
-- Scenario / static content (24.1 - 24.5, 24.9 - 24.13)
-- =============================================================================

create table scenario (
  id text primary key,
  name text not null,
  version text not null,
  description text,
  default_player_count_min int not null check (default_player_count_min > 0),
  default_player_count_max int not null check (default_player_count_max >= default_player_count_min),
  default_schedule_json jsonb not null default '{}'::jsonb,
  setting_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table faction (
  -- TODO(MVP 6 scenario editor): when supporting multiple scenarios in the same
  -- database, namespace this PK as `(scenario_id, id)` or prefix `id` with the
  -- scenario id. The same caveat applies to `map.id`, `map_score_track.id`,
  -- `map_location.id`, and `card_template.id`. Today's seed uses ids like
  -- `canopy-corp`, `earth`, `earth.war_support`, `resource.untraceable_cash`
  -- which are unique within the `crisis-mars-v1` scenario only.
  id text primary key,
  scenario_id text not null references scenario(id) on delete cascade,
  name text not null,
  short_name text not null,
  colour text,
  icon_url text,
  icon_small_url text,
  icon_colour_url text,
  public_brief text,
  common_goals jsonb not null default '[]'::jsonb,
  sort_order int not null default 0
);

create index faction_scenario_idx on faction (scenario_id, sort_order);

create table role (
  id uuid primary key default gen_random_uuid(),
  scenario_id text not null references scenario(id) on delete cascade,
  faction_id text not null references faction(id) on delete cascade,
  code text not null,
  name text not null,
  public_description text,
  private_brief text not null,
  personal_goal text,
  initiative_by_turn jsonb not null default '[]'::jsonb,
  sort_order int not null default 0,
  unique (scenario_id, code)
);

create index role_faction_idx on role (faction_id, sort_order);

create table role_availability (
  id uuid primary key default gen_random_uuid(),
  role_id uuid not null references role(id) on delete cascade,
  player_count int not null check (player_count > 0),
  is_recommended boolean not null default false,
  unique (role_id, player_count)
);

create table npc_template (
  id uuid primary key default gen_random_uuid(),
  scenario_id text not null references scenario(id) on delete cascade,
  code text not null,
  name text not null,
  default_controller text not null check (default_controller in ('earth_control', 'mars_control', 'belt_control')),
  public_description text,
  facilitator_notes text,
  unique (scenario_id, code)
);

create table map (
  id text primary key,
  scenario_id text not null references scenario(id) on delete cascade,
  name text not null,
  image_url text,
  sort_order int not null default 0
);

create table map_score_track (
  id text primary key,
  map_id text not null references map(id) on delete cascade,
  name text not null,
  description text,
  min_value int not null default 0,
  max_value int not null default 20,
  starting_value int not null default 10,
  visible_to_players boolean not null default true,
  -- A score track lives on exactly one map for ownership purposes, but a
  -- "shared" track (e.g. War Progress) may be displayed on multiple maps. List
  -- those extra map ids here so the UI can union them in. Spec section 13.5.
  shared_with_map_ids text[] not null default '{}',
  sort_order int not null default 0
);

create index map_score_track_map_idx on map_score_track (map_id, sort_order);

create table map_location (
  id text primary key,
  map_id text not null references map(id) on delete cascade,
  name text not null,
  description text,
  x numeric,
  y numeric,
  polygon_json jsonb,
  valid_for_actions boolean not null default true,
  sort_order int not null default 0
);

create index map_location_map_idx on map_location (map_id, sort_order);

create table card_template (
  id text primary key,
  scenario_id text not null references scenario(id) on delete cascade,
  card_type card_type not null,
  name text not null,
  faction_id text references faction(id) on delete set null,
  owner_role_code text,
  rules_text text,
  flavour_text text,
  impact_bonus int not null default 0,
  tradeable boolean not null default true,
  reclaimable boolean not null default true,
  image_url text
);

create index card_template_scenario_idx on card_template (scenario_id, card_type);

create table starting_resource_distribution (
  id uuid primary key default gen_random_uuid(),
  scenario_id text not null references scenario(id) on delete cascade,
  role_code text not null,
  resource_template_id text not null references card_template(id) on delete cascade,
  count int not null check (count > 0),
  unique (scenario_id, role_code, resource_template_id)
);

create table war_correspondence (
  id uuid primary key default gen_random_uuid(),
  scenario_id text not null references scenario(id) on delete cascade,
  turn int not null check (turn > 0),
  title text not null,
  public_text text not null,
  facilitator_notes text,
  suggested_effects_json jsonb not null default '[]'::jsonb,
  unique (scenario_id, turn, title)
);

-- =============================================================================
-- Session and participants (24.2, 24.6 - 24.8)
-- =============================================================================

create table game_session (
  id uuid primary key default gen_random_uuid(),
  scenario_id text not null references scenario(id),
  title text not null,
  status session_status not null default 'draft',
  current_turn int not null default 0,
  current_phase phase_kind not null default 'prologue',
  phase_started_at timestamptz,
  phase_duration_seconds int,
  phase_paused_at timestamptz,
  join_code_hash text not null,
  facilitator_code_hash text not null,
  observer_code_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index game_session_status_idx on game_session (status, updated_at desc);

create table participant (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  display_name text,
  participant_type participant_type not null,
  role_id uuid references role(id) on delete set null,
  faction_id text references faction(id) on delete set null,
  npc_template_id uuid references npc_template(id) on delete set null,
  permission_level permission_level not null default 'player',
  controlled_by_facilitator_id uuid,
  role_claimed_at timestamptz,
  role_claimed_by_name text,
  active_device_count int not null default 0,
  last_restored_at timestamptz,
  is_role_locked boolean not null default false,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),

  -- Type/shape invariants enforced at the schema layer so a bad RPC or a
  -- service-role script can't insert a corrupt row.
  constraint participant_player_has_role check (
    participant_type <> 'player'
    or (role_id is not null and faction_id is not null and npc_template_id is null)
  ),
  constraint participant_npc_has_template check (
    participant_type <> 'npc'
    or (npc_template_id is not null and role_id is null)
  ),
  constraint participant_facilitator_no_role check (
    participant_type <> 'facilitator'
    or (role_id is null and npc_template_id is null)
  ),
  constraint participant_observer_no_role check (
    participant_type <> 'observer'
    or (role_id is null and npc_template_id is null)
  )
);

-- One claimed participant per role per session (NULL role_id rows are allowed
-- to coexist - that's NPCs/facilitators/observers).
create unique index participant_role_uniq
  on participant (game_session_id, role_id)
  where role_id is not null;

-- One participant per NPC template per session.
create unique index participant_npc_uniq
  on participant (game_session_id, npc_template_id)
  where npc_template_id is not null;

create index participant_session_idx on participant (game_session_id);
create index participant_role_idx on participant (role_id) where role_id is not null;

create table participant_session (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references participant(id) on delete cascade,
  game_session_id uuid not null references game_session(id) on delete cascade,
  device_label text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  revoked_by_facilitator_id uuid references participant(id),
  -- NULL = the player has not subscribed to push on this device.
  -- '{}'::jsonb = the player explicitly disabled push on this device.
  -- Otherwise the JSON shape is a PushSubscription per the Web Push spec.
  push_subscription_json jsonb
);

create index participant_session_pid_idx on participant_session (participant_id, last_seen_at desc);

create table role_access_token (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  role_id uuid not null references role(id) on delete cascade,
  token_hash text not null,
  manual_code_hash text,
  status token_status not null default 'active',
  created_at timestamptz not null default now(),
  rotated_at timestamptz,
  rotated_by_facilitator_id uuid references participant(id),
  locked_at timestamptz,
  locked_by_facilitator_id uuid references participant(id)
);

-- Only one ACTIVE token per role per session. Rotated/locked/revoked rows live
-- alongside the active row to preserve the rotation history (spec section 6.4).
create unique index role_access_token_active_uniq
  on role_access_token (game_session_id, role_id)
  where status = 'active';

create index role_access_token_lookup_idx on role_access_token (token_hash) where status = 'active';

-- =============================================================================
-- Scores (24.11)
-- =============================================================================

create table map_score_value (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  score_track_id text not null references map_score_track(id) on delete cascade,
  current_value int not null,
  updated_at timestamptz not null default now(),
  unique (game_session_id, score_track_id)
);

create index map_score_value_session_idx on map_score_value (game_session_id);

-- =============================================================================
-- Cards (24.14)
-- =============================================================================

create table card_instance (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  card_template_id text not null references card_template(id),
  original_owner_participant_id uuid not null references participant(id) on delete restrict,
  current_holder_participant_id uuid not null references participant(id) on delete restrict,
  current_state card_state not null default 'held',
  loaned_from_participant_id uuid references participant(id),
  current_map_id text references map(id),
  current_action_id uuid,
  current_trade_id uuid,
  spent_turn int,
  spent_action_id uuid,
  spent_by_participant_id uuid references participant(id),
  accepted_by_facilitator_id uuid references participant(id),
  is_recallable boolean not null default true,
  is_reclaimable boolean not null default true,
  is_locked boolean not null default false,
  reclaimed_turn int,
  reclaimed_by_participant_id uuid references participant(id),
  qr_token_hash text,
  last_moved_by_facilitator_id uuid references participant(id),
  last_moved_reason text,
  updated_at timestamptz not null default now()
);

create index card_instance_holder_idx on card_instance (current_holder_participant_id, current_state);
create index card_instance_owner_idx on card_instance (original_owner_participant_id, current_state);
create index card_instance_session_idx on card_instance (game_session_id);
create index card_instance_qr_idx on card_instance (qr_token_hash) where qr_token_hash is not null;

-- =============================================================================
-- Per-turn participant state (24.15)
-- =============================================================================

create table participant_turn_state (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references participant(id) on delete cascade,
  game_session_id uuid not null references game_session(id) on delete cascade,
  turn int not null check (turn > 0),
  has_reclaimed_resource_this_turn boolean not null default false,
  action_card_placed boolean not null default false,
  action_card_resolved boolean not null default false,
  unique (participant_id, turn)
);

create index participant_turn_state_session_idx on participant_turn_state (game_session_id, turn);

-- =============================================================================
-- Actions (24.16 - 24.17)
-- =============================================================================

create table action_submission (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  turn int not null check (turn > 0),
  participant_id uuid not null references participant(id) on delete cascade,
  action_card_instance_id uuid not null references card_instance(id) on delete restrict,
  map_id text not null references map(id),
  location_id text references map_location(id),
  status action_status not null default 'placed',
  placed_at timestamptz not null default now(),
  called_at timestamptz,
  resolved_at timestamptz,
  unique (game_session_id, turn, participant_id)
);

create index action_submission_queue_idx on action_submission (game_session_id, turn, map_id, status);

create table action_resolution (
  id uuid primary key default gen_random_uuid(),
  action_submission_id uuid not null references action_submission(id) on delete cascade,
  fictional_action_text text,
  allies_json jsonb not null default '[]'::jsonb,
  resources_json jsonb not null default '[]'::jsonb,
  difficulty int not null default 0,
  consequence_result text,
  final_impact int,
  result_tier text,
  score_changes_json jsonb not null default '[]'::jsonb,
  fallout_text text,
  news_flag boolean not null default false,
  facilitator_id uuid references participant(id),
  resolved_at timestamptz not null default now(),
  unique (action_submission_id)
);

-- =============================================================================
-- Opportunities (24.18)
-- =============================================================================

create table opportunity (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  turn int not null,
  map_id text references map(id),
  trigger_type text,
  recipient_faction_id text references faction(id),
  recipient_npc_participant_id uuid references participant(id),
  player_text text,
  facilitator_notes text,
  option_a_text text,
  option_b_text text,
  option_a_effect_json jsonb,
  option_b_effect_json jsonb,
  status opportunity_status not null default 'pending',
  chosen_option text,
  resolved_at timestamptz
);

create index opportunity_session_idx on opportunity (game_session_id, status);

-- =============================================================================
-- Trades (24.19 - 24.20)
-- =============================================================================

create table trade_event (
  id uuid primary key default gen_random_uuid(),
  game_session_id uuid not null references game_session(id) on delete cascade,
  from_participant_id uuid not null references participant(id),
  to_participant_id uuid references participant(id),
  status trade_status not null default 'proposed',
  trade_token_hash text not null,
  confirmed_by_facilitator_id uuid references participant(id),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index trade_event_session_idx on trade_event (game_session_id, status);
create index trade_event_token_idx on trade_event (trade_token_hash) where status = 'proposed';

create table trade_item (
  id uuid primary key default gen_random_uuid(),
  trade_event_id uuid not null references trade_event(id) on delete cascade,
  card_instance_id uuid not null references card_instance(id) on delete cascade,
  direction text not null check (direction in ('from_initiator', 'to_initiator'))
);

create index trade_item_trade_idx on trade_item (trade_event_id);

-- =============================================================================
-- Audit (24.21 - 24.22)
-- =============================================================================

create table audit_event (
  id bigserial primary key,
  game_session_id uuid not null references game_session(id) on delete cascade,
  actor_participant_id uuid references participant(id),
  actor_facilitator_id uuid references participant(id),
  event_type text not null,
  event_payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index audit_event_session_idx on audit_event (game_session_id, created_at desc);

create table card_audit_event (
  id bigserial primary key,
  game_session_id uuid not null references game_session(id) on delete cascade,
  card_instance_id uuid not null references card_instance(id) on delete cascade,
  event_type text not null,
  old_state_json jsonb,
  new_state_json jsonb,
  actor_participant_id uuid references participant(id),
  actor_facilitator_id uuid references participant(id),
  reason text,
  created_at timestamptz not null default now()
);

create index card_audit_event_card_idx on card_audit_event (card_instance_id, created_at desc);
create index card_audit_event_session_idx on card_audit_event (game_session_id, created_at desc);

-- =============================================================================
-- Foreign keys deferred until late (cycle: card_instance.current_action_id -> action_submission.id)
-- =============================================================================

alter table card_instance
  add constraint card_instance_action_fk
  foreign key (current_action_id) references action_submission(id) on delete set null;

alter table card_instance
  add constraint card_instance_trade_fk
  foreign key (current_trade_id) references trade_event(id) on delete set null;

alter table participant
  add constraint participant_controller_fk
  foreign key (controlled_by_facilitator_id) references participant(id) on delete set null;

-- =============================================================================
-- Enable RLS on every table. Policies live in 0002_rls.sql.
-- =============================================================================

alter table scenario enable row level security;
alter table faction enable row level security;
alter table role enable row level security;
alter table role_availability enable row level security;
alter table npc_template enable row level security;
alter table map enable row level security;
alter table map_score_track enable row level security;
alter table map_location enable row level security;
alter table card_template enable row level security;
alter table starting_resource_distribution enable row level security;
alter table war_correspondence enable row level security;
alter table game_session enable row level security;
alter table participant enable row level security;
alter table participant_session enable row level security;
alter table role_access_token enable row level security;
alter table map_score_value enable row level security;
alter table card_instance enable row level security;
alter table participant_turn_state enable row level security;
alter table action_submission enable row level security;
alter table action_resolution enable row level security;
alter table opportunity enable row level security;
alter table trade_event enable row level security;
alter table trade_item enable row level security;
alter table audit_event enable row level security;
alter table card_audit_event enable row level security;
